# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5qRi64Egk-0WnzSNTmwaTgiTZPWiC9K
"""

scores = input().split()
count = 0

for s in scores:
    if int(s) < 60:
        count += 1

print(count)